### ISSUE TITLE
Issuede ja wiki linkimine

### ISSUE THREAD

**Issue by taneltomson** [mihkelvilismae/tartu-library-app#14]
- Wiki muutmisel tuleb lisada viited issue(de)le
- **Iga commiti puhul tuleb commiti teatesse lisada viide issuele (Nt: "Issue #xx: Parandasin selle ja tolle")**
- Samuti saab issue commitiga automaatselt kinni panna (Nt: "Issue #xx closed: Tegin ära")
- Wikit ja issuesid tuleb jooksvat uuendada, et ei tekiks lahkhelisid; nendega on hiljem palju rohkem jama. **Ehk igaüks vastutab issue lahendamisel ka wiki uuendamise eest.**

Uurige:
https://help.github.com/articles/closing-issues-via-commit-messages/
https://guides.github.com/features/issues/

**Comment by mihkelvilismae** [comment]
Selle peaks pinned postiks tegema, saab seda teha kuidagi?
