### ISSUE TITLE
Edasiste iteratsioonide kava koostamine

### ISSUE THREAD

**Issue by taneltomson** [mihkelvilismae/tartu-library-app#17]
Peame kaks iteratsiooni ette mõtlema.

**Comment by mihkelvilismae** [comment]
Mul tuli selle asja kohta üks huvitav mõte, küsige hiljem, ma magama :)

**Comment by taneltomson** [comment]
Nii?

**Comment by mihkelvilismae** [comment]
Teen seda homme pärast progekeelte kontrolltööd.
