### ISSUE TITLE
Siia paneme kirja kõik asjad, millega me projekti raames hetkel tegeleme/järgmisena tegelema hakkame :)

### ISSUE THREAD

**Issue by mihkelvilismae** [mihkelvilismae/tartu-library-app#43]
Palun täidame seda, see oleks hea lihtne moodus teada anda, et mida me teeme, et siis head üldpildi saada asjade kulgemisest :) Lisage siia postitus (igaühel on kokku seega siin teemas 1 (üks) postitus. Lisage ette nime estiäht (näiteks minul "M"). 

Ma usun et sellest on palju abi :)

- [ ] M - Teen androidi välimuse ilusaks

- [ ] M - Teen androidi funktsionaalsust paremaks 
 
- [ ]  M - Üritan kodus SOLRi tööle suva andmete peal

- [ ]  M -  Androidi peab koostama korrektse URLi kasutajat valikutest, millel abil backend suudab tulemused anda

- [ ]  M -  Androidi üleminek mock-datalt päris datale, mis tuleb backendist  

- [x] M - Mõtlen juurde asju

- [ ] M - Mõtlen täpsemalt live demo asja, ehk siis rakenduse kiirust (vana ester vs meie uus rakendus)

**Comment by taneltomson** [comment]
- [ ] T - _Peer review_ projekti koodi ülevaatus
- [ ] T - Automaattestid veebirakendusele
- [ ] T - Raamatukogu andmebaasi liidestamine

**Comment by ainika** [comment]
- [ ] A - _Peer review_ esitamine ja rakenduse üldtestimine
- [ ] A - Otsimis/selekteerimisvalik rakendusele
